<a href="https://colab.research.google.com/github/aishwaryapatle/CodeFamily-Internship/blob/main/Task%202/Task2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. NumPy N-dimensional Array**

In [1]:
import numpy as np
dt = np.dtype([('age',np.int8)])
a=np.array([(10,),(20,),(30,)], dtype = dt)
print (a['age'])

[10 20 30]


In [2]:
# create array
from numpy import array
# create array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


**2. Functions to Create Arrays**

1. Empty

In [3]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2. Zeros

In [4]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


3. Ones

In [5]:
# create one array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


**3. Combining Arrays**

1. Vertical Stack


In [6]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)


[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


2. Horizontal Stack

In [7]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


**1. From List to Arrays**

1. One-Dimensional List to Array

In [8]:
# create one-dimensional array
from numpy import array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


2. Two-Dimensional List of Lists to Array

In [9]:
# create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


**2.  Array Indexing**

1. One-Dimensional Indexing

In [10]:
# index a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])

11
55


In [12]:
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[4])

55


In [13]:
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


2. Two-Dimensional Indexing

In [14]:
# index two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,0])

11


In [15]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,])

[11 22]


**3. Array Slicing**

1. One-Dimensional Slicing

In [16]:
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


In [17]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [19]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


2. Two-Dimensional Slicing

In [18]:
# split input and output data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


Split Train and Test Rows
*   train = data[:split, :]
*   test = data[split:, :]



In [20]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


**4. Array Reshaping**

1. Data Shape

In [21]:
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [22]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


In [23]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


2. Reshape 1D to 2D Array

In [24]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


3. Reshape 2D to 3D Array

data.reshape((data.shape[0], data.shape[1], 1))



In [25]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)
